version: "3.7"
services:
  server:
    image: ghcr.io/bluemap-minecraft/bluemap:v5.7@sha256:bcd15a23651f45eca1b699636f570fbbb5c50ac4f9db74e8ed73639f7cc82ee0
    command: -r -u -w
    ports:
      - 18100:8100
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/web:/app/web
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world:/app/world
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world/DIM-1:/world_nether
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world/DIM1:/world_the_end
    restart: on-failure
