version: "3.7"
services:
  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:master
    container_name: minecraft-bluemap
    command: -r -u -w
    ports:
      - 18100:8100
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
      - ${APP_DATA_DIR}/data:/app/data
      - ${APP_DATA_DIR}/web:/app/web
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world:/app/world
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world/DIM-1:/world_nether
      - ${UMBREL_ROOT}/app-data/hsukuo-minecraft/data/world/DIM1:/world_the_end
    restart: on-failure
