version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server:java21@sha256:06a047d7b62f5bf55a31ffc73f114d3fdafdf569cda5623eadf143d7f2f3c506
    # container_name: hsukuo-minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      SERVER_PORT: "25565"
    ports:
      - "25565:25565"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: on-failure
    stdin_open: true
    tty: true