version: "3.7"
services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: hsukuo-minecraft-server
    environment:
      EULA: "TRUE"
      VERSION: "1.20.1"
      SERVER_PORT: "25565"
    ports:
      - "25565:25565"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: on-failure
    stdin_open: true
    tty: true